#!/bin/bash
set -e

if [[ "$(uname)" == "Darwin" ]]; then
  ./bootstraps/osx.sh
elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
  ./bootstraps/linux.sh
fi

mkdir -p ~/.vim/autoload

# restart shell
su -l `whoami`
