#!/bin/bash
set -e

if [[ "$(uname)" == "Darwin" ]]; then
  ./bootstraps/osx.sh
elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
  ./bootstraps/linux.sh
fi

mkdir -p ~/.vim/autoload
curl -fLo ~/.vim/autoload/plug.vim \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim -c PlugInstall -c quitall

# restart shell
su -l `whoami`
