cd ~/Projects/oc/opencounter
launch zsh -c "nvim .;zsh"

new_tab build
layout horizontal
cd ~/Projects/oc/opencounter
launch zsh -c "yarn start; zsh"

title solargraph
launch zsh -c "solargraph socket;zsh"
