cd ~/Projects/oc/opencounter
launch zsh -c "vim .;zsh"

new_tab build
layout horizontal
cd ~/Projects/oc/opencounter
launch bash -c "yarn start; bash"

title solargraph
launch bash -c "solargraph socket;zsh"
